const promptOne = [
    [`Who's most likely to`, `embarrass themselves in front of a crush?`],
    [`Who's most likely to`, `end up on a realtiy TV show?`],
    [`Who's most likely to`, `forget someone's birthday?`],
    [`Who's most likely to`, `get a tattoo on a whim?`],
    [`Who's most likely to`, `fall asleep in the middle of a conversation?`],
    [`Drink if you've`, `sent a text to the wrong person`],
    [`Drink if you've`, `been kicked out of a bar or club`],
    [`Drink if you've`, `drunk dailed someone`],
    [`Drink if you've`, `had a crush on someone in this room`],
    [`Drink if you've`, `kissed someone in this room`],
    [`Drink if you've`, `sent a risque text message`],
    [`Drink if you've`, `had a one-night stand`],
    [`Drink if you've`, `lied about your relationship status`],
    [`Drink if you've`, `hooked up in a public place`]
]; //bell's prompts

const promptTwo = [
    [`Who's most likely to`, `text their ex "I miss you" after one drink?`],
    [`Who's most likely to`, `laugh at a joke they don't understand?`],
    [`Who's most likely to`, `send a screenshot back to the person they were gossiping about?`],
    [`Who's most likely to`, `flirt their way out of a parking ticket?`],
    [`Who's most likely to`, `fake an accent to impress someone?`],
    [`Who's most likely to`, `show up to a house party an hour early by mistake?`],
    [`Who's most likely to`, `forget where they parked and have a full-on meltdown?`],
    [`Drink if you've`, `pretended to know something just to sound smart`],
    [`Drink if you've`, `been caught stalking someones profile`],
    [`Drink if you've`, `had a dream about someone in this room and didn't tell them`]
]; //isa's prompts

const promptThree = [
    [`Who's most likely to`, `be single the longest`],
    [`Who's most likely to`, `be the best kisser`],
    [`Who's most likely to`, `fall in love with someone they don't know`],
    [`Drink if you've`, `trown up in a taxi`],
    [`Drink if you've`, `send a nude in the last two weeks `],
    [`Drink if you've`, `been fined`],
    [`Drink if you've`, `been fired`],
    [`Drink if you've`, `kissed a colleague`],
    [`Drink if you've`, `had a completely free date`],
    [`Drink if you've`, `spent the most money on ordering food in the last month`],
    [`Drink if you've`, `been caught lying about your age or have caugt someone lying about their age`],
    [`Drink if you've`, `formerly played a stupid instrument, especially the flute`],
    [`Drink if you've`, `got your driverslicense`],
    [`Task`, `take a bodyshot from the person to your right`],
    [`Task`, `search a word of your choice in the WhatsApp of the person to your right`],
    [`Task`, `give everybody a shot, one of the shots is water. guess who has the shot of water. if you guessed wrong, take a drink`],
    [`Task`, `mix the drink of the person to your left and right and drink it`],
    [`Task`, `everybody passes their shirt/top/blouse to the person to their right`]
]; //lous' prompts

const promptFour = [
    [`Who's most likely to`, `find their true love on a dating app`],
    [`Who's most likely to`, `to become a celebrity (for what?)`],
    [`Who's most likely to`, `be the fastest at building IKEA furniture`],
    [`Who's most likely to`, `not survive if they had to switch to a flip phone`],
    [`Who's most likely to`, `go home first because they are mentally a grandma/grandpa`],
    [`Who's most likely to`, `be the best host`],
    [`Drink if you've`, `sent a text to the wrong person (tell the story)`],
    [`Drink if you've`, `went on a date because you felt bad`],
    [`Drink if you've`, `ghosted someone`],
    [`Drink if you've`, `had to escape a bad date`]
]; //gesa's prompts

const promptFive = [
    [`Who's most likely to`, `start a family first`],
    [`Who's most likely to`, `be the mom/dad of the group`],
    [`Who's most likely to`, `get lost on a trip`],
    [`Who's most likely to`, `lose their student card`],
    [`Who's most likely to`, `need therapy after studying`],
    [`Who's most likely to`, `camp out for concert tickets`],
    [`Who's most likely to`, `have the messiest room`],
    [`Drink if you've`, `got dying plants`],
    [`Drink if you've`, `had a curfew living at home`],
    [`Drink if you've`, `saved someone with a nickname in your phone`],
    [`Drink if you're`, `still on your first drink`],
    [`Drink if you've`, `stayed up all night reading`],
    [`Drink if you've`, `had a memorable encounter with a fortune teller/psychic`]
]; //ilvy's prompts

const promptSeven = [
    [`Drink if you've`, `gone on a date just for a free meal`],
    [`Drink if you've`, `said "I love you" by accident`],
    [`Drink if you've`, `forgotten someone's name after a date`],
    [`Drink if you've`, `written a love letter`],
    [`Task`, `tell your worst date story`],
    [`Task`, `for the three questions hold hands with the person to your left`],
    [`Task`, `make a shot for the person to your right`],
    [`Task`, `name your current crush or take 4 sips`],
    [`Task`, `name your celebrity crush`],
    [`Task`, `switch seats with the person opposite of you`]
]

const promptSix = [
    [`Drink if you've`, `gone skinny dipping`],
    [`Drink if you're`, `single`],
    [`Drink if you've`, `met up with someone from a dating app`],
    [`Drink if you've`, `been dumped over the phone`],
    [`Drink if you've`, `had a blind date`],
    [`Drink if you`, `believe in love at first sight`],
    [`Drink if you're`, `wearing black underwear`],
    [`Drink if you've`, `successfully used a pick-up line`],
    [`Drink if you've`, `recieved a handwritten love letter`],
    [`Drink if you've`, `had romantic feelings for someone of the same sex`],
    [`Drink if you've`, `hooked up with more than one person in the same night`],
    [`Who's most likely to`, `be the biggest romantic`],
    [`Who's most likely to`, `read erotica`],
    [`Who's most likely to`, `get married first`],
    [`Who's most likely to`, `have attachment issues`]
]

const promptMostLikely = [
    [`Who's most likely to`, `be the biggest romantic`],
    [`Who's most likely to`, `read erotica`],
    [`Who's most likely to`, `get married first`],
    [`Who's most likely to`, `have attachment issues`],
    [`Who's most likely to`, `start a family first`],
    [`Who's most likely to`, `be the mom/dad of the group`],
    [`Who's most likely to`, `get lost on a trip`],
    [`Who's most likely to`, `lose their student card`],
    [`Who's most likely to`, `need therapy after studying`],
    [`Who's most likely to`, `camp out for concert tickets`],
    [`Who's most likely to`, `have the messiest room`],
    [`Who's most likely to`, `find their true love on a dating app`],
    [`Who's most likely to`, `to become a celebrity (for what?)`],
    [`Who's most likely to`, `be the fastest at building IKEA furniture`],
    [`Who's most likely to`, `not survive if they had to switch to a flip phone`],
    [`Who's most likely to`, `go home first because they are mentally a grandma/grandpa`],
    [`Who's most likely to`, `be the best host`],
    [`Drink if you've`, `sent a text to the wrong person (tell the story)`],
    [`Who's most likely to`, `text their ex "I miss you" after one drink?`],
    [`Who's most likely to`, `laugh at a joke they don't understand?`],
    [`Who's most likely to`, `send a screenshot back to the person they were gossiping about?`],
    [`Who's most likely to`, `flirt their way out of a parking ticket?`],
    [`Who's most likely to`, `fake an accent to impress someone?`],
    [`Who's most likely to`, `show up to a house party an hour early by mistake?`],
    [`Who's most likely to`, `forget where they parked and have a full-on meltdown?`],
    [`Who's most likely to`, `embarrass themselves in front of a crush?`],
    [`Who's most likely to`, `end up on a realtiy TV show?`],
    [`Who's most likely to`, `forget someone's birthday?`],
    [`Who's most likely to`, `get a tattoo on a whim?`],
    [`Who's most likely to`, `fall asleep in the middle of a conversation?`],
    [`Who's most likely to`, `eat somethinig of the ground?`],
    [`Who's most likely to`, `have a foot fetish?`],
    [`Who's most likely to`, `lock themselves out the house?`],
    [`Who's most likely to`, `embarrass themselves on a first date?`],
    [`Who's most likely to`, `pull an irish-goodbye?`],
    [`Who's most likely to`, `date two people at once?`],
    [`Who's most likely to`, `hook up with their boss?`],
    [`Who's most likely to`, `build a sex dungeon?`],
    [`Who's most likely to`, `make the first move?`],
    [`Who's most likely to`, `sleep with a colleague?`],
    [`Who's most likely to`, `cheat on their parnet?`],
    [`Who's most likely to`, `be the loadest during sex?`],
    [`Who's most likely to`, `end up in jail?`],
    [`Who's most likely to`, `win in a sprinting race?`],
    [`Who's most likely to`, `marry someone for the money?`],
    [`Who's most likely to`, `get married within a month of meeting someone?`],
    [`Who's most likely to`, `flirt with someone to get free drinks?`],
    [`Who's most likely to`, `dance on a table or podium?`],
    [`Who's most likely to`, `go on a sidequest on a night out?`],
    [`Who's most likely to`, ``]



    // [`Who's most likely to`, ``],
]

const promptDrinkIf = [
    [`Drink if you've`, `gone skinny dipping`],
    [`Drink if you're`, `single`],
    [`Drink if you've`, `met up with someone from a dating app`],
    [`Drink if you've`, `been dumped over the phone`],
    [`Drink if you've`, `had a blind date`],
    [`Drink if you`, `believe in love at first sight`],
    [`Drink if you're`, `wearing black underwear`],
    [`Drink if you've`, `successfully used a pick-up line`],
    [`Drink if you've`, `recieved a handwritten love letter`],
    [`Drink if you've`, `had romantic feelings for someone of the same sex`],
    [`Drink if you've`, `hooked up with more than one person in the same night`],
    [`Drink if you've`, `gone on a date just for a free meal`],
    [`Drink if you've`, `said "I love you" by accident`],
    [`Drink if you've`, `forgotten someone's name after a date`],
    [`Drink if you've`, `written a love letter`],
    [`Drink if you've`, `got dying plants`],
    [`Drink if you've`, `had a curfew living at home`],
    [`Drink if you've`, `saved someone with a nickname in your phone`],
    [`Drink if you're`, `still on your first drink`],
    [`Drink if you've`, `stayed up all night reading`],
    [`Drink if you've`, `had a memorable encounter with a fortune teller/psychic`],
    [`Drink if you've`, `sent a text to the wrong person (tell the story)`],
    [`Drink if you've`, `went on a date because you felt bad`],
    [`Drink if you've`, `ghosted someone`],
    [`Drink if you've`, `had to escape a bad date`],
    [`Drink if you've`, `trown up in a taxi`],
    [`Drink if you've`, `send a nude in the last two weeks `],
    [`Drink if you've`, `been fined`],
    [`Drink if you've`, `been fired`],
    [`Drink if you've`, `kissed a colleague`],
    [`Drink if you've`, `had a completely free date`],
    [`Drink if you've`, `spent the most money on ordering food in the last month`],
    [`Drink if you've`, `been caught lying about your age or have caugt someone lying about their age`],
    [`Drink if you've`, `formerly played a stupid instrument, especially the flute`],
    [`Drink if you've`, `got your driverslicense`],
    [`Drink if you've`, `sent a text to the wrong person`],
    [`Drink if you've`, `been kicked out of a bar or club`],
    [`Drink if you've`, `drunk dailed someone`],
    [`Drink if you've`, `had a crush on someone in this room`],
    [`Drink if you've`, `kissed someone in this room`],
    [`Drink if you've`, `sent a risque text message`],
    [`Drink if you've`, `had a one-night stand`],
    [`Drink if you've`, `lied about your relationship status`],
    [`Drink if you've`, `hooked up in a public place`],
    [`Drink if you've`, `most recently kissed someone`],
    [`Drink if you've`, `blond hair`],
    [`Drink if you've`, `brown hair`],
    [`Drink if you've`, `red hair`],
    [`Drink if you've`, `never gotten flowers`],
    [`Drink if you've`, `gone back to an ex`],
    [`Drink if you've`, `intentionally forgotten something as a reason to come back`],
    [`Drink if you've`, `lied about your age or hight`],
    [`Drink if you've`, `flirted with someone while knowing they were taken`],
    [`Drink if you've`, `been denied a taxi`],
    [`Drink if you've`, `driven drunk`],
    [`Drink if you've`, `drunk an inappropriate amount at a company event`],
    [`Drink if you've`, `gotten drunk alone`],
    [`Drink if you've`, `drunk in the morning`],
    [`Drink if you've`, `the worst alcohol tolerance here`],
    [`Drink if you've`, `sent a text you later regretted`],
    [`Drink if you've`, `failed a driving test`]

    // [`Drink if you've`, ``],
]

const promptTask = [
    [`Task`, `take a bodyshot from the person to your right`],
    [`Task`, `search a word of your choice in the WhatsApp of the person to your right`],
    [`Task`, `give everybody a shot, one of the shots is water. guess who has the shot of water. if you guessed wrong, take a drink`],
    [`Task`, `mix the drink of the person to your left and right and drink it`],
    [`Task`, `everybody passes their shirt/top/blouse to the person to their right`],
    [`Task`, `make a drink for the person to your right`],
    [`Task`, `name your current crush or take 4 sips`],
    [`Task`, `name your celebrity crush`],
    [`Task`, `switch seats with the person opposite of you`],
    [`Task`, `go on a date with <a href="https://www.instagram.com/wyncko_roozeboom">@Wycnko</a>`],
    [`Task`, `chug a beer if Gesa is in the room`],
    [`Task`, `everybody who is on their phone has to chug a beer (this phone not included)`],
    [`Task`, `start a waterfall`],
    [`Task`, `hold a beer in your right hand, you cannot talk or let go until it's empty`],
    [`Task`, `microwave your drink`],
    [`Task`, `the group can decide a dare for you (including a punishment for not completing the dare)`],
    [`Task`, `roll a dice, drink that number of sips`],
    [`Task`, `compliment the person to your right`]

    // [`Task`, ``],
]

export { promptDrinkIf, promptMostLikely, promptTask};